---
title: "TidyR-Day2"
author: "Meg Hemmerlein"
date: "2026-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## R Markdown

command + return / control + enter --> run a single line

play button --> run all code in a code chunk

triangle + line button --> run all previous code chunks

```{r load data}

tortoise_body_condition <- read.csv("cleaned_tortoiseBC.csv")

clutch_size <- read.csv("cleaned_clutchSize.csv")

```



```{r Questions of Interest 1}

#### IS it easier to recapture male or female tortoises?

#### Let's plan out what we want
# Which dataset should we use? tortoise_body_condition

# Which variables? sex and individual

# What do we actually need to do? parse info of m or f -> count

# What functions should we use? group_by , summarize 

Sex_recapture <- tortoise_body_condition %>%
  group_by(sex, season) %>%
  summarise(total_recapture = n())

Sex_recapture

```



```{r Questions of Interest 2}
#### Do recaptures happen more often in spring or summer?

#### Let's plan out what we want

# Which dataset should we use?  tortoise_body_condition

# Which variables?  seasons 

# What do we actually need to do? group_by season

# What functions should we use? group_by (season -> summarize)

# For one individual 

# For all


Season_recapture <- tortoise_body_condition %>%
  group_by(season) %>%
  summarise(tortoises = n()) 

# For all

Season_recapture <- tortoise_body_condition %>%
  group_by(individual, season) %>%
  summarise(tortoises = n())

# For one individual 

Season_recapture <- tortoise_body_condition %>%
  filter(individual == "100") %>%
  group_by(season) %>%
  summarise(tortoises = n())
  

```



```{r Question of Interest 3}

#### Between the springs of 2016 and 2017, did the turtles grow differently based on locality?

#### Let's plan out what we want

# Which dataset should we use? tortoise_body_condition

# Which variables? season (spring), year (2016 and 2017), locality , straight_carapace_length_mm (2017 - 2016)

# What do we actually need to do? filter (spring, 2016 and 2017), finding the difference between years (convert back to wide data format to do math) -> pivot.wider -> difference -> summarize for each location our growth between the two years

# What functions should we use?


SCL <- tortoise_body_condition %>%
  filter(season == "Spring") %>%
  filter(year %in% c(2016,2017)) %>%
  group_by(individual,year,locality) %>%
  summarise(
    SCL = first(straight_carapace_length_mm), 
    .groups = "drop"
    ) 

SCL_wide <- SCL %>%
  pivot_wider(
    names_from = year,
    values_from = SCL
  )

# Clean up wide data (rewrite SCL_wide)

SCL_wide <- SCL_wide %>%
  drop_na()

# Column rename

SCL_wide <- SCL_wide %>%
  drop_na() %>%
  rename(
    yr_2016 = `2016`,
    yr_2017 = `2017`) %>%
  mutate(growth_2017_2016 = yr_2017 - yr_2016)



#difference -> summarize for each location our growth between the two years

SCL_wide %>%
  group_by(locality) %>%
  summarise(
    avg_growth = mean(growth_2017_2016)
  )

  
#check = tortoise_body_condition %>%
 # filter(individual== "1054") %>%
  #filter(season == "Spring")

```



```{r Factor Relevel Example}

mycolors <- c(
  "Beach" = "gold",
  "Konjsko" = "lightblue",
  "Plateau" = "#72B000"
)

# Plot
# Hmm that's okay, but I'd like the order to be different
clutch_size %>%
ggplot(aes(locality, eggs, fill = locality)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.1, size = 3, alpha = 0.5) +
  scale_fill_manual(values = mycolors)

#ggsave("clutch.png", width = 8, height = 6, units = "in")

#Check class of locality
class(clutch_size$locality) 

#Convert to factor
clutch_size$locality = as.factor(clutch_size$locality) 

#Check conversion
class(clutch_size$locality) 

#Check factor levels
levels(clutch_size$locality)

#Relevel factors
clutch_size = clutch_size %>%
  mutate(locality = fct_relevel(locality, "Beach", "Plateau", "Konjsko"))

#Check factor levels
levels(clutch_size$locality)

#Plot
clutch_size %>%
ggplot(aes(locality, eggs, fill = locality)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.1, size = 3, alpha = 0.5) +
  scale_fill_manual(values = mycolors)

#ggsave("clutch_relevel.png", width = 8, height = 6, units = "in")

clutch_size = clutch_size %>%
  mutate(locality = fct_recode(locality,
                               "SunnyBeach" = "Beach",
                               "ScaryPlateau" = "Plateau", 
                               "CoolKonjsko" = "Konjsko"))
mycolors2 <- c(
  "SunnyBeach" = "gold",
  "CoolKonjsko" = "lightblue",
  "ScaryPlateau" = "#72B000"
)

clutch_size %>%
ggplot(aes(locality, eggs, fill = locality)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.1, size = 3, alpha = 0.5) +
  scale_fill_manual(values = mycolors2)

#ggsave("clutch_recode.png", width = 8, height = 6, units = "in")

```

